[package]
name = "arp-cache"
version = "0.1.0"
authors = ["markafarrell <mark.andrew.farrell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
pnet = "0.26.0"